import "./globals.css";
import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import Header from "./components/header/header";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} relative max-w-[1440px] w-full my-0 mx-auto h-[7000px] theme`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
